server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
      open-in-view: true
      hibernate:
        ddl-auto: update  # => 한번 생성한후엔 update로 설정할것. 실행시마다 drop ~ create 수행
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          # org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl : 변수명(username)을 그대로 필드로 넣어줌
          # org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy : myEamil => my_email 컬럼으로 만들어줌(카멜표기법(Camel case))
        use-new-id-generator-mappings: false  # false: jpa설정을 따라가지 않는다. true:jpa 기본 넘버링 전략을 따라간다.
      show-sql: false  # 로그에 쿼리 생성을 보여줌
      properties:
        hibernate.format_sql: true  # 쿼리를 pretty 하게

  jackson:
    serialization:
      fail-on-empty-beans: false

#카카오 로그인시 비밀번호통일(운영시에는 노출되면 안됨)
cos:
  key: cos1234

#  http:
#    encoding:
#      charset : UTF-8
#      enabled : true
#      force: true
